### PR TITLE
New functions for creating ticket and adding followup

### PR DESCRIPTION
**Pull request by Geo-Ron**
Creating new functions to:

1. Create a new ticket (and associate an item with it)
2. Add followups to existing tickets

### CODE REVIEW

**Comment by Geo-Ron** [comment]
Functions:
- New-GLPIToolsTicket
- Update-GLPIToolsTicket
- Add-GLPIToolsTicketTask
- Update-GLPIToolsTicketTask
- Get-GLPIToolsTicketTask
- Add-GLPIToolsTicketItem
- Add-GLPIToolsTicketFollowUp
- Add-GLPIToolsTicketSolution

**Comment by Geo-Ron** [comment]
@wpietrzakpl, I believe this set is ready.

**Review by wpietrzakpl — APPROVED** [review]

**Comment by Chouille** [comment]
New functions are not added in functions to export in psm1 ;)

**Comment by Geo-Ron** [comment]
Hahaha. I see now...

**Comment by wpietrzakpl** [comment]
new module version been pushed to the powershellgallery

**Pull request merged**
